### ISSUE TITLE
Helm version update

### ISSUE THREAD

**Issue by zweihan** [masmovil/masorange_rules_helm#71]
Hi, wondering if you would take a PR that updates Helm to 3.13.3?

**Comment by danigar** [comment]
Sorry for the late response. Sure, your PR will be more than welcome!

**Comment by danigar** [comment]
Hi @zweihan. I'll close this issue as we have already upgraded helm version to the most recent version `v3.16.3`. You can find this changes with new rules version `v1.2.0`.

**Comment by zweihan** [comment]
Thanks!
